In [1]:
import pyspark

In [27]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import sum, avg

spark = SparkSession.builder.appName("Experience level and salary analysis").getOrCreate()

read_data = spark.read.csv("/Users/Krishnaveni/Downloads/ds_salaries.csv",  header=True, inferSchema=True)

#get the total and avg values of the employees based on experience level and job title
aggrigated_avg_sal = read_data.groupBy("experience_level", "job_title") \
                        .agg(avg("salary_in_usd").alias("Avg_Salary_USD") , sum("salary_in_usd").alias("Total_Salary_USD"))\
                        .orderBy("Avg_Salary_USD", ascending=False)
print("aggrigated_avg_sal based on the experience_leveland job_title  ")
aggrigated_avg_sal.show(5)


#Compare the salaries of different employment types

Compare_salaries_employment_types = read_data.groupBy("employment_type")\
                                    .agg(avg("salary_in_usd").alias("Avg_Salary_USD"),sum("salary_in_usd").alias("Total_Salary_USD"))\
                                    .orderBy("Avg_Salary_USD", ascending=False)
print("Compare_salaries based on the employment_types")
Compare_salaries_employment_types.show(5)


#impact of remote work on salaries
impact_of_remoteWork_on_Sal = read_data.groupBy("remote_ratio")\
                                    .agg(avg("salary_in_usd").alias("Avg_Salary_USD"),sum("salary_in_usd").alias("Total_Salary_USD"))\
                                    .orderBy("Avg_Salary_USD", ascending=False)
print("impact_of_remoteWork on Salaries")
impact_of_remoteWork_on_Sal.show(5)


#Compare salaries across different countries
Compare_salaries_Diferent_countries = read_data.groupBy("company_location")\
                                    .agg(avg("salary_in_usd").alias("Avg_Salary_USD"),sum("salary_in_usd").alias("Total_Salary_USD"))\
                                    .orderBy("Avg_Salary_USD", ascending=False)
print("Compare_salaries based on the Diferent_countries")
Compare_salaries_Diferent_countries.show(5)


Compare_salaries_Diferent_countries_Size = read_data.groupBy("company_size")\
                                    .agg(avg("salary_in_usd").alias("Avg_Salary_USD"),sum("salary_in_usd").alias("Total_Salary_USD"))\
                                    .orderBy("Avg_Salary_USD", ascending=False)
print("Compare_salaries based on the Diferent_countries_size")
Compare_salaries_Diferent_countries_Size.show(5)


#aggrigated_avg_sal.write.csv("/Users/Krishnaveni/results/aggrigated_avg_sal.csv", header=True)
#Compare_salaries_employment_types.write.csv("/Users/Krishnaveni/results/Compare_salaries_employment_types.csv", header=True)
#impact_of_remoteWork_on_Sal.write.csv("/Users/Krishnaveni/results/impact_of_remoteWork_on_Sal.csv", header=True)
#Compare_salaries_Diferent_countries.write.csv("/Users/Krishnaveni/results/Compare_salaries_Diferent_countries.csv", header=True)
#Compare_salaries_Diferent_countries_Size.write.csv("/Users/Krishnaveni/results/Compare_salaries_Diferent_countries_Size.csv", header=True)

aggrigated_avg_sal based on the experience_leveland job_title
+----------------+--------------------+------------------+----------------+
|experience_level|           job_title|    Avg_Salary_USD|Total_Salary_USD|
+----------------+--------------------+------------------+----------------+
|              EX|Principal Data Sc...|          416000.0|          416000|
|              SE| Data Analytics Lead|          405000.0|          405000|
|              SE|Data Science Tech...|          375000.0|          375000|
|              SE|Cloud Data Architect|          250000.0|          250000|
|              EX|        Head of Data|238183.33333333334|         1429100|
+----------------+--------------------+------------------+----------------+
only showing top 5 rows

Compare_salaries based on the employment_types
+---------------+------------------+----------------+
|employment_type|    Avg_Salary_USD|Total_Salary_USD|
+---------------+------------------+----------------+
|             FT| 138314.1995696611|       514252194|
|             CT|          113446.9|         1134469|
|             FL|           51807.8|          518078|
|             PT|39533.705882352944|          672073|
+---------------+------------------+----------------+

impact_of_remoteWork on Salaries
+------------+------------------+----------------+
|remote_ratio|    Avg_Salary_USD|Total_Salary_USD|
+------------+------------------+----------------+
|           0|144316.20228809153|       277520057|
|         100|136481.45283018867|       224239027|
|          50| 78400.68783068784|        14817730|
+------------+------------------+----------------+

Compare_salaries based on the Diferent_countries
+----------------+------------------+----------------+
|company_location|    Avg_Salary_USD|Total_Salary_USD|
+----------------+------------------+----------------+
|              IL|          271446.5|          542893|
|              PR|          167500.0|          670000|
|              US|151822.00953947369|       461538909|
|              RU|140333.33333333334|          421000|
|              CA| 131917.6896551724|        11476839|
+----------------+------------------+----------------+
only showing top 5 rows

Compare_salaries based on the Diferent_countries_size
+------------+------------------+----------------+
|company_size|    Avg_Salary_USD|Total_Salary_USD|
+------------+------------------+----------------+
|           M|143130.54836663496|       451290619|
|           L|118300.98237885462|        53708646|
|           S| 78226.68243243243|        11577549|
+------------+------------------+----------------+